config/routes.rb
ApproximationCalculator::Application.routes.draw do

  root :to => 'problems#new'
  
  resources :feedback, :only => [:new, :create]

  devise_for :users, :skip => [:registrations]
  
  as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :problems
  resources :users do
    member do
      get 'problems'
    end
  end
  
  get "help/about"
  get "problems/new"
  match "/data", to: "problems#data"
  match "/exportCSV", to: "problems#exportCSV"
  match "/student_problems", to: "users#student_problems"

  

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  belongs_to :user
  attr_accessible :a, :answer, :b, :sign, :time, :user, :x, :y, :mistakes, :user_id
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
	before_filter :authenticate_user!	
	require("Rounding.rb")
	require("csv")
	
  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @problems }
    end
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem = Problem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/new
  # GET /problems/new.json
  def new
    @problem = Problem.new
	@problem.sign = '+'

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/1/edit
  def edit
    @problem = Problem.find(params[:id])
  end
  
  # GET /problems/1/retry
  def retry
	@problem = Problem.find(params[:id])
  end
  
  # GET /problems/data
  def data
	@problems = Problem.all
	@users = User.all		
	incorrect = []
	correct = []
	@users.each do |u|
		totalproblems = u.problems
		correctproblems = totalproblems.where(:mistakes=>0)
		incorrectproblems = totalproblems - correctproblems
		incorrect<<[u.username, incorrectproblems.count]
		correct<<[u.username, correctproblems.count]
	end
	@graph = LazyHighCharts::HighChart.new('column') do |f|
		f.series(:name=>'Incorrect',:data=>incorrect,:color=>'#0d233a')
		f.series(:name=>'Correct',:data=>correct,:color=>'#2f7ed8')
	f.xAxis(:type=>"category", :labels=>{:staggerLines=>2})
    f.title(:text=>"Problems per student")
	f.chart(:zoomType=>"x", :resetZoomButton=>{:position=>{:y=>-25}})

    ###  Options for Bar
    ### f.options[:chart][:defaultSeriesType] = "bar"
    ### f.plot_options({:series=>{:stacking=>"normal"}}) 

    ## or options for column
    f.options[:chart][:defaultSeriesType] = "column"
    f.plot_options(:column=>{:stacking=>"normal"})
	end
  end
  
  #GET /problems/exportCSV
  def exportCSV
	csv_string = CSV.generate do |csv|
		csv << ["User Name", "Original A", "Original B", "Sign", "Rounded X", "Rounded Y", "Final Answer", "Correct?", "Time Taken", "Time Stamp"]
		Problem.all.each do |problem|
			username = User.find(problem.user_id).username
			csv << [username, problem.a, problem.b, problem.sign, problem.x, problem.y, problem.answer, problem.mistakes==0, problem.time, problem.created_at]
		end
	end
	send_data(csv_string, :filename=>'StudentData_' + Date.today.to_s + '.csv', :type=>'text/csv', :disposition=>'attachment')
  end

  # POST /problems
  # POST /problems.json
  def create  
    @problem = current_user.problems.create(params[:problem])
	allow = { :to5 => true, :to10 => true, :to15 => true, :to25 => true } #default
	rounding = Rounding.new(@problem.a, @problem.b, @problem.sign, allow, 0.15)

    respond_to do |format|
		@problem.mistakes = 0
		if @problem.sign == '+'
			tight = (!rounding.tightAddEst?(@problem.x, @problem.y))
			realAnswer = @problem.a + @problem.b
			incorrect = (@problem.x + @problem.y != @problem.answer)
		elsif @problem.sign == '-'
			tight = (!rounding.tightSubEst?(@problem.x, @problem.y))
			realAnswer = @problem.a - @problem.b
			incorrect = (@problem.x - @problem.y != @problem.answer)
		elsif @problem.sign == '*'
			tight = (!rounding.tightMultiEst?(@problem.x, @problem.y))
			realAnswer = @problem.a * @problem.b
			incorrect = (@problem.x * @problem.y != @problem.answer)
		elsif @problem.sign == '/'
			tight = (!rounding.tightDivEst?(@problem.x, @problem.y))	
			realAnswer = (@problem.a.to_f / @problem.b).round(2)	
			incorrect = (@problem.x / @problem.y != @problem.answer)
		end
		@mistakes = [incorrect, (!rounding.goodRound?(@problem.x, @problem.y)), tight]
		if @mistakes.include?(true)			
			aOrig = @problem.a #Copy the problem's features into temp variables -- so the form doesn't reset
			bOrig = @problem.b
			xOrig = @problem.x
			yOrig = @problem.y
			signOrig = @problem.sign
			@problem.mistakes += 100 if @mistakes[0]
			@problem.mistakes += 20 if @mistakes[1]
			@problem.mistakes += 3 if @mistakes[2]
			if @problem.save
				@problem = Problem.new(params[:problem])
				@problem.a = aOrig
				@problem.b = bOrig
				@problem.x = xOrig
				@problem.y = yOrig	
				@problem.sign = signOrig
				@problem.errors.add(:Tightness, ": Your estimate isn't close enough to the actual. Try a different rounding in Step 2.") if @mistakes[2]
				@problem.errors.add(:Rounding, ": There's a mistake in your rounded problem set. Check your work in Step 2.") if @mistakes[1]
				@problem.errors.add(:Incorrect, ": The answer you gave isn't correct for the rounded problem set you provided.") if @mistakes[0]
				format.html { render action: "new" }
			else
				format.html { render action: "new" }
				format.json { render json: @problem.errors, status: :unprocessable_entity }
			end
		else
			if @problem.save
				@problem = Problem.new(params[:problem])
				@success = ("Good job! The actual answer was " + realAnswer.to_s + ".")
				format.html { render action: "new" }
				#flash[:notice] = ("Good job! The actual answer is " + realAnswer.to_s + ".")
				#format.html { redirect_to :action=>"new" }
				#format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
				#format.json { render json: @problem, status: :created, location: @problem }
			else
				format.html { render action: "new" }
				format.json { render json: @problem.errors, status: :unprocessable_entity }
			end
		end
    end
  end

  # PUT /problems/1
  # PUT /problems/1.json
  def update
    @problem = Problem.find(params[:id])

    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem = Problem.find(params[:id])
    @problem.destroy

    respond_to do |format|
      format.html { redirect_to problems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_calculator.html.erb
<%= form_for(@problem) do |f| %>

  <script>
  var start;
  window.onload=function(){
	$('#transBtn').popover({title: "Sorry!", content: "All numbers (including answers) have to be between -2,147,483,647 and 2,147,483,647.", placement: "bottom", trigger: "manual"});
	$('#ansBtn').popover({title: "Sorry!", content: "All numbers (including answers) have to be between -2,147,483,647 and 2,147,483,647.", placement: "bottom", trigger: "manual"});
	var a=document.getElementById("problem_a");
	a.select();
  }
  function init(s){
	setSign(s)
	if (s=='-') $("#minusbtn").button('toggle');
	else if (s=='*') $("#multibtn").button('toggle');
	else if (s=='/') $("#divbtn").button('toggle');
	else $("#plusbtn").button('toggle');
  }
  function setSign(s){	
	document.getElementById("problem_sign").value = s;
	if (s=='-'){
		document.getElementById("sign").innerHTML = '&#8211';
		document.getElementById("sign2").innerHTML = '&#8211';		
	}
	else if (s=='*'){
		document.getElementById("sign").innerHTML = '&#215';
		document.getElementById("sign2").innerHTML = '&#215';
	}
	else if (s=='/'){
		document.getElementById("sign").innerHTML = '&#247';
		document.getElementById("sign2").innerHTML = '&#247';
	}
	else{
		document.getElementById("sign").innerHTML = s;
		document.getElementById("sign2").innerHTML = s;
	}
  }
  function clearFields(){
	document.getElementById("problem_x").value="";
	document.getElementById("problem_y").value="";
	document.getElementById("problem_answer").value="";
	$('#transBtn').popover('hide');
  }
  function validate(x){
	var notEmpty = /^\s*-?\d+\s*$/;
	return (notEmpty.test(x));
  }
  function numsTooBig(){
	var a=document.getElementById("problem_a").value;
	var b=document.getElementById("problem_b").value;
	var x=document.getElementById("problem_x").value;
	var y=document.getElementById("problem_y").value;
	var f=document.getElementById("problem_answer").value;
	if (a>2147483647 || a<-2147483647 || b>2147483647 || b<-2147483647 || x>2147483647 || x<-2147483647 || y>2147483647 || y<-2147483647 || f>2147483647 || f<-2147483647){
		return true;
	}
  }
  function func(){
	var tooBig = numsTooBig();
	if (!tooBig) {$('#transBtn').popover('hide');}
	else {$('#transBtn').popover('show');}
	var a = document.getElementById("problem_a");
	var b = document.getElementById("problem_b");
	if (validate(a.value) && validate(b.value) && !tooBig){
		start = Date.now();
		a.disabled = true;
		b.disabled = true;
		document.getElementById("nextbutton").style.display = "none";
		document.getElementById("step2").style.display = "block";
		$(".alert-success").alert('close');
		document.getElementById("problem_x").select();
	}
  }
  function resetForm(){
	$('#transBtn').popover('hide');
	$('#ansBtn').popover('hide');
	var a = document.getElementById("problem_a");
	var b = document.getElementById("problem_b");
	a.disabled = null;
	b.disabled = null;
	a.value="";
	b.value="";
	clearFields();
	document.getElementById("nextbutton").style.display = "block";
	document.getElementById("step2").style.display = "none";
	$(".alert").alert('close');
	a.select();
  }
  function ansclick(){
	var tooBig = numsTooBig();
	if (!tooBig) {$('#ansBtn').popover('hide');}
	else {$('#ansBtn').popover('show');}
	var x = document.getElementById("problem_x").value;
	var y = document.getElementById("problem_y").value;
	var answer = document.getElementById("problem_answer").value;
	if (validate(x) && validate(y) && validate(answer) && !tooBig){
		var elapsed = Date.now() - start;
		document.getElementById("problem_a").disabled = false;
		document.getElementById("problem_b").disabled = false;
		document.getElementById("problem_time").value = elapsed;
		document.forms[0].submit();
	}
  }
  </script>
  <div id="sidebar">
	<div id="operator-btns" class="btn-group btn-group-vertical" data-toggle="buttons-radio">
		<button id="plusbtn" class="btn sign-btn" type="button" onclick="setSign('+');"><h1>+</h1></button>
		<button id="minusbtn" class="btn sign-btn" type="button" onclick="setSign('-');"><h1>&#8211;</h1></button>
		<button id="multibtn" class="btn sign-btn" type="button" onclick="setSign('*');"><h1>&#215;</h1></button>
		<button id="divbtn" class="btn sign-btn" type="button" onclick="setSign('/');"><h1>&#247</h1></button> 
	</div>
  </div>
  
	<div id="instructions">
		Step 1: Enter a problem<br>               
		Step 2: Round the problem<br>              
		Step 3: Answer the rounded problem     
	</div>
  
  <div id="section1">
	<div id="field1">
		<%= f.number_field :a, :onchange=>"clearFields();" %> 
	</div>
	<div id="op1">
		<h2><span id="sign"></span></h2>
	</div>
	<div id="field2">
		<%= f.number_field :b, :onchange=>"clearFields();" %>
	</div>
	<div id="step2" style = "display:none;">
		<div id="field3">
			<%= f.number_field :x %>
		</div>
		<div id="field4">
			<%= f.number_field :y %>
		</div>
		<div id="op2">
			<h2><span id="sign2"></span></h2>
		</div>
		<div id="field5">
			<%= f.number_field :answer %>
		</div>
		<%= f.hidden_field :user_id %>
		<%= f.hidden_field :time %>
		<%= f.hidden_field :sign %>
		<script> init(document.getElementById("problem_sign").value); </script>
		<div id="answerbutton">
			<button class="btn btn-primary" name="ansBtn" id="ansBtn" type="button" onclick="ansclick();">Check Answer</button>
			<button class="btn btn-danger" type="button" onclick="resetForm();">Reset</button>
		</div>
	</div>
	<div id="nextbutton">
		<button class="btn" name="transition" id="transBtn" type="button" onclick="func();">Next Step</button>
		<button class="btn btn-danger" type="button" onclick="resetForm();">Reset</button>
	</div>	
  </div>
   
  <% if @success %>
    <div class="message alert alert-success fade in">
	  <button class="close" data-dismiss="alert">×</button>
      <h5><%= @success.to_s %></h5>
    </div>
  <% end %>
    
  <% if @problem.errors.any? %>
    <div class="message alert alert-error fade in">
	  <button class="close" data-dismiss="alert">×</button>
      <h5>We noticed <%= pluralize(@problem.errors.count, "problem") %> with your answer:</h5>
      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<% end %>

app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :a %><br />
    <%= f.number_field :a %>
  </div>
  <div class="field">
    <%= f.label :b %><br />
    <%= f.number_field :b %>
  </div>
  <div class="field">
    <%= f.label :x %><br />
    <%= f.number_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.number_field :y %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.number_field :answer %>
  </div>
  <div class="field">
    <%= f.label :sign %><br />
    <%= f.text_field :sign %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.number_field :time %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problems/_graph.html.erb
<%= high_chart("my_id4", @graph) %>

app/views/problems/data.html.erb
<div class="btn-group">
	<button class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#">
		Visualizations
		<span class="caret"></span>
	</button>
	<ul class="dropdown-menu">
		<li><a href="#">Problems per student</a></li>
		<li><a href="#">Some Option #2</a></li>
		<li><a href="#">Some Option #3</a></li>
	</ul>
</div>
<a class="btn" style="margin-left:5px" href="<%= exportCSV_path %>">
	Export as CSV
</a>
<%= render 'graph' %>

app/views/problems/edit.html.erb
<h1>Editing problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<h1>Listing problems</h1>

<table>
  <tr>
	<th>user_id</id>
    <th>A</th>
    <th>B</th>
    <th>X</th>
    <th>Y</th>
    <th>Answer</th>
    <th>Sign</th>
    <th>Time Taken</th>
    <th>User</th>
	<th>Timestamp</th>
	<th>Correct?</th>
	<th>Mistake Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @problems.each do |problem| %>
  <tr>
	<td><%= problem.user_id %></td>
    <td><%= problem.a %></td>
    <td><%= problem.b %></td>
    <td><%= problem.x %></td>
    <td><%= problem.y %></td>
    <td><%= problem.answer %></td>
    <td><%= problem.sign %></td>
    <td><%= problem.time %></td>
    <td><%= problem.user %></td>
    <td><%= problem.created_at %></td>
	<td><%= problem.mistakes==0 %></td>
    <td><%= problem.mistakes==0 ? "n/a" : problem.mistakes %></td>
    <td><%= link_to 'Show', problem %></td>
    <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
    <td><%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Problem', new_problem_path %>

app/views/problems/new.html.erb
<%= render 'calculator' %>

<div id="history">
	<%= link_to 'History', problems_path %>
</div>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>A:</b>
  <%= @problem.a %>
</p>

<p>
  <b>B:</b>
  <%= @problem.b %>
</p>

<p>
  <b>X:</b>
  <%= @problem.x %>
</p>

<p>
  <b>Y:</b>
  <%= @problem.y %>
</p>

<p>
  <b>Answer:</b>
  <%= @problem.answer %>
</p>

<p>
  <b>Sign:</b>
  <%= @problem.sign %>
</p>

<p>
  <b>Time:</b>
  <%= @problem.time %>
</p>

<p>
  <b>User:</b>
  <%= @problem.user %>
</p>


<%= link_to 'Edit', edit_problem_path(@problem) %> |
<%= link_to 'Back', problems_path %>