config/routes.rb
ApproximationCalculator::Application.routes.draw do

  root :to => 'problems#new'
  
  resources :feedback, :only => [:new, :create]

  devise_for :users, :skip => [:registrations]
  
  as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :problems
  resources :users do
    member do
      get 'problems'
    end
  end
  
  get "help/about"
  get "problems/new"
  match "/data", to: "problems#data"
  match "/exportCSV", to: "problems#exportCSV"
  match "/student_problems", to: "users#student_problems"

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :problems
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable


  
  # in User.rb
  attr_accessible :email, :password, :password_confirmation, :remember_me,
				:username, :role, :teacher, :admin
  # attr_accessible :title, :body

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def new
  end

  def create
    @user = User.create(params[:user])
    if @user.role == ""
      @user.role = "student"
    end
    @user.save!
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id]).where(:role => "teacher" || "gen_admin")
    @problems = Problem.all 
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def student_problems
    @problems = User.find(params[:user]).problems.all
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>User Created</h1>

app/views/users/edit.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, :as => resource_name, :url => user_registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :teacher %><br />
  <%= f.text_field :teacher, :autofocus => true %></div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div><%= f.submit "Update" %></div>
<% end %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table id="users_index">
<thead>
  <tr>
  	<th>Username: </th>
    <th>Email: </th>
    <th>Teacher: </th>
    <th>Role: </th>
    <th>Admin? </th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @users.each do |user| %>
  <% if user.teacher == current_user.teacher || current_user.role == "admin" %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.teacher %></td>
    <td><%= user.role %></td>
    <td><%= user.admin %></td>
    <td><%= link_to 'Problems', student_problems_path(user: user) %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
<% end %>
</tbody>
</table>

<br />

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for(resource, :as => resource_name, :url => user_registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.label :username %><br />
  <%= f.text_field :username %></div>

  <div><%= f.label :teacher %><br />
  <%= f.text_field :teacher %></div>

  <% if current_user.role == "admin" || "teacher" %>
    <div><%= f.label :role %><br />
    <%= f.select :role, [['Admin', 'admin'], ['Teacher', 'teacher'], ['Student', 'student']] %></div>
  <% end %>

  <div><%= f.submit "Sign up" %></div>
<% end %>

app/views/users/student_problems.html.erb
<h1>Student Problem Set</h1>

<table id="problem_set">
<thead>
  <tr>
	<th>user_id</th>
    <th>A</th>
    <th>B</th>
    <th>X</th>
    <th>Y</th>
    <th>Answer</th>
    <th>Sign</th>
    <th>Time Taken</th>
    <th>Timestamp</th>
    <th>Correct?</th>
    <th>Mistake Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @problems.each do |problem| %>
  <tr>
	<td><%= problem.user_id %></td>
    <td><%= problem.a %></td>
    <td><%= problem.b %></td>
    <td><%= problem.x %></td>
    <td><%= problem.y %></td>
    <td><%= problem.answer %></td>
    <td><%= problem.sign %></td>
    <td><%= problem.time %></td>
    <td><%= problem.created_at %></td>
    <td><%= problem.mistakes==0 %></td>
    <td><%= problem.mistakes==0 ? "n/a" : problem.mistakes %></td>
    <td><%= link_to 'Show', problem %></td>
    <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
    <td><%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />
