config/routes.rb
ApproximationCalculator::Application.routes.draw do

  root :to => 'problems#new'
  
  resources :feedback, :only => [:new, :create]

  devise_for :users, :skip => [:registrations]
  
  as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :problems
  resources :users do
    member do
      get 'problems'
    end
  end
  
  get "help/about"
  get "problems/new"
  match "/data", to: "problems#data"
  match "/exportCSV", to: "problems#exportCSV"
  match "/student_problems", to: "users#student_problems"

  

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) && !(msg.blank?)%>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}"%>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
	<%= link_to('About', help_about_path) %>
	</li>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit Account', edit_user_registration_path) %>
    </li>
  <% end %>
  <% if user_signed_in? and current_user.role == "admin" || current_user.role == "teacher" %>
    <li>
    <%= link_to('View Students', users_path ) %>
    </li>
  <% end %>
  <% if user_signed_in? and current_user.role == "admin" || current_user.role == "teacher" %>
    <li>
    <%= link_to('New User', new_user_path ) %>
    </li>
  <% end %>
  <% if user_signed_in? and current_user.role == "admin" || current_user.role == "teacher" %>
	 <li>
	 <%= link_to('Student Data', data_path) %>
	 </li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Approximation Calculator" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
	<%= feedback_includes %>
	<%= feedback_tab(:position => 'right') %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>

  <body> 
	<%= image_tag("logo.png", :alt => "logos") %>
    <header class="navbar">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= yield %>
              <%= render 'layouts/messages' %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>